#!/bin/bash -e
#
# Import all actors needed for the imp5hcd workflow
#


import_svn_actor()
{
  name="$1.tar"
  file="$2/$name"
  path="$3/$name"
  importFlags="$4 $5 $6 $7 $8"

  echo "
----------------------------------------------------
IMPORT ACTOR COMMANDS:
  svn export $path $file
  import_actor $importFlags  $file
  rm -f $file
----------------------------------------------------
"

  svn export $path $file
  import_actor $importFlags  $file
  rm -f $file
}

import_svn_actor_group()
{
  groupname=$1

  if  [ $groupname == "electron_physics" ]; then
     actors=$electron_physics
  elif  [ $groupname == "ion_physics" ]; then
     actors=$ion_physics
  else
     actors=$tools
  fi
  for actor in $actors; do
    import_svn_actor ${actor} ${tmpDir} ${repository}/${groupname}/${actor}  $FLAGS
  done
}

#--------------------------------------------------
# INPUT
#--------------------------------------------------

if [ $DATAVERSION_TAG == 4.10b.10 ]; then
  repository=https://gforge.efda-itm.eu/svn/kepleractors/branches/4.10b.10/heating
else
  repository=https://gforge.efda-itm.eu/svn/kepleractors/trunk/4.10b/heating
fi
FLAGS=" -p -f "

electron_physics="gray travis TORAYFOM" #"relax  torbeamwaves"
ion_physics="iccoup  nuclearsim nbisim bbnbi nemo risk spot ascot4serial ascot4parallel Cyrano LIONslice icdept itmfp1d StixReDist eve_s" #  afsiFusionSourceIntegrator
# MATYI START
#ion_physics="iccoup afsi nuclearsim nbisim bbnbi nemo risk spot ascot4serial ascot4parallel Cyrano LIONslice icdept itmfp1d StixReDist eve_s" #  afsiFusionSourceIntegrator
# MATYI END
#cpogenerators="codeparam2nbi  emptyantennas  emptywall emptydistribution  emptydistsource  emptywaves  ICantennawrite  nbisetup  nbisetupmini  nbifiller  wallsetup  writeECant  writeLHlaunchs"
tools="emptydistsource  emptywaves  emptycorefast emptycoresource nbifiller  addECant addICant wallFiller hcd2coresource  hcd2corefast  waves2sources  merger4distribution  merger4distsource sliceEquilibrium sliceCoreprof sliceCoreimpur"

# MATYI START
#tools="emptydistsource emptydistribution  emptywaves  emptycorefast emptycoresource nbifiller  addECant addICant wallFiller hcd2coresource  hcd2corefast  waves2sources  merger4distribution  merger4distsource sliceEquilibrium sliceCoreprof sliceCoreimpur"
# MATYI END

# IMPORTANT: There has to be one and only one actor in ${final_tools_actor}. The actor will be imported last and with a flag that forces kepler to recompile so it's ready to run.
final_tools_actor="merger4waves"

#--------------------------------------------------
# TEMPORARY DIRECTORY FOR STORING ACTOR FILES WHILE
# IMPORTING TO KEPLER
#--------------------------------------------------
tmpDir=tmp_import_imp5hcd_actors_$$
mkdir $tmpDir

#--------------------------------------------------
# IMPORT ACTORS TO KEPLER
#--------------------------------------------------

import_svn_actor_group electron_physics
import_svn_actor_group ion_physics 
import_svn_actor_group tools

FLAGS=-f

# MATYI START
# missing actors
final_tools_actor="merger4waves"
import_svn_actor       ${final_tools_actor} ${tmpDir} ${repository}/tools/${final_tools_actor} $FLAGS

repository=https://gforge.efda-itm.eu/svn/kepleractors/trunk/4.10b/heating
final_tools_actor="afsi"
import_svn_actor       ${final_tools_actor} ${tmpDir} ${repository}/ion_physics/${final_tools_actor} $FLAGS

final_tools_actor="emptydistribution"
import_svn_actor       ${final_tools_actor} ${tmpDir} ${repository}/tools/${final_tools_actor} $FLAGS
# MATYI END

rm -rf $tmpDir
